### ISSUE TITLE
Empty date of birth not alllowed in 1.3.0

### ISSUE THREAD

**Issue by lab-incert** [ehn-dcc-development/ehn-dcc-schema#101]
Hello,

The pattern in the date of birth for the V1.3.0 is wrong as it does not accept empty field, however the specification adopted by the eHN states otherwise.

The pattern is:  "pattern": "^(19|20)\\d\\d(-\\d\\d){0,2}$",

Empty field is not accepted.

Also, in the example, the empty field "" shall be added.

**Comment by gabywh** [comment]
Correct, but we already knew.
As the name implies, this is a release candidate and not an official release yet.

**Comment by vaubaehn** [comment]
Dear @gabywh 
> Correct, but we already knew.

How can we know that you know?

> As the name implies, this is a release candidate and not an official release yet.

Do you want contributions to release candidates? Or just to versions that are already live and in production and cause problems due to bugs?

Short answer would highly bee appreciated.
Kind regards, v.

**Comment by gabywh** [comment]
Op zo 13 jun. 2021 12:07 schreef vaubaehn ***@***.***>:

> Dear @gabywh <https://github.com/gabywh>
>
> Correct, but we already knew.
>
> How can we know that you know?
>
> As the name implies, this is a release candidate and not an official
> release yet.
>
> Do you want contributions to release candidates?
>

N

> Or just to versions that are already live and in production and cause
> problems due to bugs?
>
Y



Short answer would highly bee appreciated.

**Comment by vaubaehn** [comment]
Hi @gabywh , thanks for your (shortest possible) reply.
Good luck with your project.
Kind regards
