### ISSUE TITLE
Translation of Value Set Display Fields

### ISSUE THREAD

**Issue by SZoerner** [ehn-dcc-development/ehn-dcc-schema#112]
I see the [value sets provide a language attribute](https://github.com/ehn-dcc-development/ehn-dcc-schema/blob/a603410d760fefc9073931c8c807759d9714c136/valuesets/vaccine-medicinal-product.json#L7) - currently set to "en" for all entries.
Is it intended to support translations of the value set fields in the future? Several MS indicated that they would be willing to contribute a translation. If so: do we have a process for this already?

**Comment by gabywh** [comment]
Translations are intended to be supported hence the lang attribute.
However, whether that comes from the same official source (Semantic SG) for the value sets or is left to Member States to support translations I do not know (but suspect the latter). I can raise it as an issue and see if we can get some clarification.

**Comment by gabywh** [comment]
@kruzikh this is one for ehn-dcc-valuesets

**Comment by kruzikh** [comment]
Actually @gabywh, Translation was never a topic discussed within the SGS if I remember correctly. I think that we created it as a  technical attribute in the json schema to support possible translation of the VS into different languages in the future. If we want to use it now, we should open discussion about the process of translation (M/S will be responsible most probably) and distribution (if we want to distribute multilingual version of the VS) throught the DCCG. I see that rather as a technical issue that should be open within the TIO. Or should I open it in SGS? What do you think?

**Comment by gabywh** [comment]
Correct, never was discussed. The idea was to at least mark for any user agent what language the free text fields are in - can be used in all kinds of ways.

Process of translation: my initial feeling was that it would be MS who are responsible, but then again if this is to be EU wide e.g. I am a German person living in the Netherlands with my phone in French (which it is, actually, never got around to changing it lol!) then I think it could also make sense to have an EU centrally managed translation, like most (all?) other EU docs.

Distribution: yes DCCG would be the obvious hosting point. So e.g. I could have the Italian official app (interesting choice given recent events in the Italian parliament!) but have the user interface in French and the Italian app should be able to load the French versions for display. All standard stuff on string resources, been around for decades, so I guess we should re-use it.

Several possibilities for implementing this in user agents (e.g. mobile phone clients).

One for TIO as no real semantics here (it is "just" a text label for display, the "real" values are the key values)

Also one for ehn-dcc-valuesets and not for ehn-dcc-schema.

**Comment by gabywh** [comment]
Continued in https://github.com/ehn-dcc-development/ehn-dcc-valuesets/issues/13
