### ISSUE TITLE
Kosovo - valueset country-2-codes.json

### ISSUE THREAD

**Issue by rafalgra** [ehn-dcc-development/ehn-dcc-schema#113]
@gabywh @kruzikh Kosovo shouldn't be in the dictionary country-2-codes? Alternatively, what to do when someone has had a vaccination in Kosovo and wants to get a certificate in a member state? What should be completed in the attribute 'co'?

**Comment by gabywh** [comment]
1. Discussed elsewhere: https://github.com/ehn-dcc-development/ehn-dcc-schema/issues/111#issuecomment-867080840
2. As communicated in more than one meeting last week, valuesets have moved to: https://github.com/ehn-dcc-development/ehn-dcc-valuesets. They are still here as "deprecated" and will be removed if there is a further versioned release of this schema
