### ISSUE TITLE
Support of entries with unicode characters from the "Halfwidth and Fullwidth" Forms block

### ISSUE THREAD

**Issue by ggrund-tsi** [ehn-dcc-development/ehn-dcc-schema#122]
The current covid-19-lab-test-manufacturer-and-name valuset contains an entry with unicode characters from the "Halfwidth and Fullwidth" Forms block.

The following entry has a fullwidth left and right paranthesis instead of a common left/right paranthesis:

"2139":{"display":"HANGZHOU LYSUN BIOTECHNOLOGY CO., LTD., COVID-19 Antigen Rapid Test Device（Colloidal Gold）" .......

Expected:
Entries in the valueset should use the common latin block U+0000 to U+007F.
Left Paranthesis expected character: U+0028 instead of U+FF08
Right Paranthesis expected character: U+0029 instead of U+FF09

**Comment by dslmeinte** [comment]
Sorry @ggrund-tsi : apparently, I didn't see this issue coming in.

Because it pertains to the value sets, can you repost this issue over at https://github.com/ehn-dcc-development/ehn-dcc-valuesets ?

**Comment by ggrund-tsi** [comment]
Hi @dslmeinte, I will do as suggested. Thx
