### ISSUE TITLE
Problem during Make

### ISSUE THREAD

**Issue by Pat7584** [ehn-dcc-development/ehn-dcc-schema#127]
Hi
Thank you for welcome me
I need some help
I use windows 10, Visual studio
I have some trouble with the make, i obtain
Checking JSON formatting...
DCC.Core.Types.schema.json DCC.Core.Types.schema.json.tmp differ: byte 2, line 1
Please reformat DCC.Core.Types.schema.json
DCC.schema.json DCC.schema.json.tmp differ: byte 2, line 1
Please reformat DCC.schema.json
DCC.Types.schema.json DCC.Types.schema.json.tmp differ: byte 2, line 1
Please reformat DCC.Types.schema.json
DCC.ValueSets.schema.json DCC.ValueSets.schema.json.tmp differ: byte 2, line 1
and so on
and at the end
/node_modules/.bin/ajv -c ajv-formats --spec=draft2020 --strict=false test -s DCC.combined-schema.json -d "examples/vaccination/*.json" --valid
error: C:\Users\patri\Documents\ehn-dcc-schema-release-1.3.0 (1)\ehn-dcc-schema-release-1.3.0\DCC.combined-schema.json: Unexpected end of JSON input
make: *** [Makefile:23: test] Error 2

Is it a problem with JQ ?
Thank you for any help

**Comment by ryanbnl** [comment]
I'd recommend using the Windows Subsystem for Linux, that's what I do (or a linux box).
