### ISSUE TITLE
Missing descriptions of "tg" property in test and recovery groups

### ISSUE THREAD

**Issue by Jakub-KK** [ehn-dcc-development/ehn-dcc-schema#129]
Currently (schema v1.3.0 and proposed v1.3.1) only "vaccination_entry" has property "tg" containing "description":
```
"vaccination_entry": {
  [...]
  "properties": {
    "tg": {
      "description": "disease or agent targeted",
      "$ref": "#/$defs/disease-agent-targeted"
    },
```
"test_entry" and "recovery_entry" both lack "description" property - only "$ref" is provided:
```
"test_entry": {
  [...]
  "properties": {
    "tg": {
      "$ref": "#/$defs/disease-agent-targeted"
    },
```
When using automated tools that parse schema to provide human-readable form of DCCs using contained descriptions, this omission results in output that has "tg" not described - the schema is not complete for this usage in its published form.
Other properties common to all groups, such as "is" or "ci" already have the same descriptions duplicated in every group, "tg" property having description everywhere would be more consistent than at present when only vaccination group has it.
"test_entry" and "recovery_entry" should contain "tg" with the same description as "vaccination_entry".

**Comment by dslmeinte** [comment]
Fixed by PR #130
