### ISSUE TITLE
Link does not exist

### ISSUE THREAD

**Issue by benlaurie** [ehn-dcc-development/ehn-dcc-schema#133]
https://github.com/ehn-dcc-development/ehn-dcc-schema/blob/a603410d760fefc9073931c8c807759d9714c136/DCC.schema.json#L46 - the URL does not exist.

**Comment by dslmeinte** [comment]
The reference resolves to https://github.com/ehn-dcc-development/ehn-dcc-schema/blob/release/1.3.1/DCC.Core.Types.schema.json#L17
The host URL indeed does not exist: see https://github.com/ehn-dcc-development/ehn-dcc-schema/wiki/FAQ#schema-location

**Comment by dslmeinte** [comment]
@benlaurie  I'd like to clarify, and check my short answer (I wanted to answer, but was in a meeting) from before a bit more with you:

- Is that FAQ entry sufficient as an answer as to why the URL in the schema IDs doesn't exist?

In any case: thanks for having an in-depth look at this. We believe it's correct, but we also realize it's easy to goof up.

**Comment by benlaurie** [comment]
Yes, indeed - though one does have to question which genius thought that making URIs and URLs indistinguishable was a good idea.

**Comment by dslmeinte** [comment]
@benlaurie Yeah, it's one of those “gifts” (due to histerical reasons) that keep on giving, indeed.
