### ISSUE TITLE
Please add Novavax - Medicinal Product and Producer

### ISSUE THREAD

**Issue by VFederau** [ehn-dcc-development/ehn-dcc-schema#134]
Please add Novavax - Mecial Product and Producer
EU declare it as valid since 21.12.2021 .

And maybe you should declare in 
https://github.com/ehn-dcc-development/ehn-dcc-schema/blob/release/1.3.0/valuesets/vaccine-medicinal-product.json
how many doses needs to be activ and a additional array for "booster" - with Date and maybe the product also.
Greetings Victoria

**Comment by dslmeinte** [comment]
Hi @VFederau , The value sets have been moved to a separate repo: https://github.com/ehn-dcc-development/ehn-dcc-valuesets 
Updating these value sets is done according to a process that involves the eHN's Semantic Group getting notified of approval of new vaccines (ultimately) by the EMA. So, this will happen, but not instigated through an issue on this repo.

As for the suggestion to include data about the number of vaccines required, etc., in the value set: that's deemed outside of the scope of the value sets, which primarily aim to fixate the IDs with which vaccines, etc., are known, so referring to these in the DCC can be done reliably.
