### ISSUE TITLE
outdated/problem with a link

### ISSUE THREAD

**Issue by albertoabellagarcia** [ehn-dcc-development/ehn-dcc-schema#135]
The link 
[https://id.uvci.eu/DCC.Core.Types.schema.json#/$defs/person_name](https://id.uvci.eu/DCC.Core.Types.schema.json#/$defs/person_name) have either a ssl problem or is outdated.
for the attribute 'v' 
 "description": "Vaccination Group",

Additionally 
[https://id.uvci.eu/DCC.Types.schema.json#/$defs/test_entry](https://id.uvci.eu/DCC.Types.schema.json#/$defs/test_entry)
is a 404 error directly
for the attribute 't'
 "description": "Test Group"

and the same for 
[https://id.uvci.eu/DCC.Types.schema.json#/$defs/recovery_entry](https://id.uvci.eu/DCC.Types.schema.json#/$defs/recovery_entry)
for the attribute 'r'
 "description": "Recovery Group",

**Comment by dslmeinte** [comment]
Please see https://github.com/ehn-dcc-development/ehn-dcc-schema/wiki/FAQ#schema-location

**Comment by albertoabellagarcia** [comment]
thank you for the quick answer. 
What you link in your reply is right when using URI in a linked data context, but it is not valid when is the link of a definition of a $ref element in a schema. 
This schema is simply wrong, it cannot validate any payload. (it is also true that it could be easily get fixed by changing the domain) but now what is in the repo is wrong. If you want me to make the PR I will be happy to do it.

**Comment by dslmeinte** [comment]
The [combined schema](https://github.com/ehn-dcc-development/ehn-dcc-schema/blob/release/1.3.0/DCC.combined-schema.json) is fine and used for validation.
Improvements are welcomed: feel free to make a PR.

**Comment by albertoabellagarcia** [comment]
Certainly, the combined schema is right), so I would close the issue.

I have a doubt about the country attribute
      "valueset-uri": "valuesets/country-2-codes.json"

I got that this is like an enumeration, shouldn't be an actual enumeration instead of an ad-hoc list of objects, that in fact, it does not validate anything?
I am rather sure that if you include the value 'XZ' in the 'co' attribute it will be validated while this is not a valid ISO-3166 code.

**Comment by dslmeinte** [comment]
OK, I'll close it.

You're right about the value sets being underspecified through their JSON Schema. The value sets are defined in [another repository](https://github.com/ehn-dcc-development/ehn-dcc-valuesets) but we haven't finished splitting that off properly yet, so there are some technical loose ends, and some duplication. The value sets are actually properly specified in official EU documents, so in practice it poses no problems.
