### ISSUE TITLE
array of a single element?

### ISSUE THREAD

**Issue by albertoabellagarcia** [ehn-dcc-development/ehn-dcc-schema#136]
In the [combined-schema](https://github.com/ehn-dcc-development/ehn-dcc-schema/blob/release/1.3.0/DCC.combined-schema.json) the attribute 'v' is an array with a maximum number of elements of 1 and a minimum of 1. 
Shouldn't be simpler to say that it is a simple object instead of an array of 1 element?  
And the same for attributes t and r. 
What is the idea behind this complex use?

**Comment by jschlyter** [comment]
At first the schema allowed for combinations of vaccinations, tests and recovery statements. Rather late in the process, this was limited to a single one.

**Comment by karanagai** [comment]
I am curious if this is what causes problems with recording booster shots in the DCC

**Comment by dslmeinte** [comment]
@karanagai What problems are you referring to?

**Comment by karanagai** [comment]
@dslmeinte my apologies if I am wrong on that, but it seems currently the EU DCC does not support storing the booster information. At least this is what they are saying to us here in Ireland. And also "we are working on it". I went to check the schema and in fairness I was a bit surprised by that "array of 1 element" type, and thought may be that was the reason.

**Comment by dslmeinte** [comment]
@karanagai Ah, well...yes and no.

Purely from a data perspective it would be best if all _events_ (vaccinations, tests, recoveries) were in the DCC. From a privacy perspective that's extremely undesirable. The reason to limit a DCC to 1 event was partly to reduce complexity (e.g., business rules get a lot trickier to formulate and implement for multiple events), and partly to avoid privacy issues.

Boosters now have to be encoded as n/n (meaning `dn` = `sd` = n in the fields of a vaccination entry), with n > 2. There are some exceptions to this, notably for the Janssen vaccine. This amendment to the relevant EU Regulation is quite recent, which might be the reason for “we're working on it”.

**Comment by CybitsBlockchain** [comment]
Not to mention the space limitation you have on the CBOR / QR Code

**Comment by karanagai** [comment]
@dslmeinte thanks for the explanation!

@CybitsBlockchain I thought so as well, thanks.

**Comment by albertoabellagarcia** [comment]
Are you considering it as optional to include a verification by a DLT signature? 
You can browse [this schema](https://github.com/smart-data-models/dataModel.DistributedLedgerTech/blob/master/DLTtxReceipt/schema.json) for a DLT receipt.

**Comment by dslmeinte** [comment]
@albertoabellagarcia There are currently no plans to make a DLT signature possible.
