### ISSUE TITLE
Inconsistencies for PCR tests DGC and Rapid Test DGC

### ISSUE THREAD

**Issue by lab-incert** [ehn-dcc-development/ehn-dcc-schema#68]
Hello,

In LU, we face some issues regarding the definition of the JSON schema for the test DGC (PCR and Rapid Test).
The following points shall be discuss.

To summarize, as it is defined right now, the JSON schema for the test DGc has the following mandatory fields:
- tg --> disease targeted
- tt --> type of test
- sc --> date/time of the sample collection
- tr --> date/time of the test result
- tc --> testing center
- co --> country of test
- is --> certificate issuer
- ci --> UVCI

and the optional fields:
- nm --> test name
- ma --> RAT test name and manufacturer

For the two optional fields, the information is get from https://covid-19-diagnostics.jrc.ec.europa.eu/devices.

If we look at the examples within this repository (test-naa.json and test-rat.json), we observe the following:

1. for test-naa.json
      - "nm" field is present, and seems to contain the "Commercial Name" from https://covid-19-diagnostics.jrc.ec.europa.eu/devices
2.  for test-rat.json
      - "ma" field is present, and contains the "ID Device" https://covid-19-diagnostics.jrc.ec.europa.eu/devices
      -  a "dr" field is present, which seems to be a typo as it should be "tr", but this field is actually optional for rapid test

Thus, we have the following remarks: 
1. In the PCR test DGC, the JSON schema contains the Commercial Name. In the Rapid Test DGC, the JSON schema contains the ID_Device. This is inconsistent, as in both types of test, the ID_Device points to the Commercial Name and the Manufacturer Name. To avoid redundancy and save some space within the QR Code, the ID_Device only should be used within the JSON schema, for both types of test.

2. The "tr" field for Rapid Test DGC is optional, not mandatory. This shall be changed within the specification of the JSON schema (in Luxembourg, we will not have this information given by the concerned parties). 

Thanks in advance for clarifying this.

**Comment by gabywh** [comment]
https://github.com/ehn-digital-green-development/ehn-dgc-schema/releases/tag/1.2.0
Field `dr` dropped

**Comment by gabywh** [comment]
As discussed 7 June 2021: schema plus valuesets being updated
